"""Initial migration

Revision ID: 9c50cfea7119
Revises: 
Create Date: 2025-12-30 18:29:44.512963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c50cfea7119'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors_json', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('open_access', sa.Integer(), nullable=True),
    sa.Column('pdf_object_key', sa.Text(), nullable=True),
    sa.Column('pdf_sha256', sa.String(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('created_at_unix', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_docs_canonical_id'), 'docs', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_docs_doc_id'), 'docs', ['doc_id'], unique=False)
    op.create_index(op.f('ix_docs_doc_type'), 'docs', ['doc_type'], unique=False)
    op.create_index(op.f('ix_docs_pdf_sha256'), 'docs', ['pdf_sha256'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.Integer(), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.doc_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_chunks_chunk_id'), 'chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunks_doc_id'), 'chunks', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_doc_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_docs_pdf_sha256'), table_name='docs')
    op.drop_index(op.f('ix_docs_doc_type'), table_name='docs')
    op.drop_index(op.f('ix_docs_doc_id'), table_name='docs')
    op.drop_index(op.f('ix_docs_canonical_id'), table_name='docs')
    op.drop_table('docs')
    # ### end Alembic commands ###
